name: Build and Test (No Dependency Submission)

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Make Maven wrapper executable
      run: |
        if [ -f "./mvnw" ]; then
          chmod +x ./mvnw
          echo "Maven wrapper found and made executable"
        else
          echo "No Maven wrapper found, will use system Maven"
        fi

    - name: Build with Maven
      run: |
        if [ -f "./mvnw" ]; then
          ./mvnw clean compile -DskipTests
        else
          mvn clean compile -DskipTests
        fi

    - name: Run tests
      run: |
        if [ -f "./mvnw" ]; then
          ./mvnw test
        else
          mvn test
        fi

    - name: Generate test report
      if: always()
      run: |
        if [ -f "./mvnw" ]; then
          ./mvnw surefire-report:report
        else
          mvn surefire-report:report
        fi
